version: '3'

services:
  flask-api:
    build:
      context: /home/hashbury/Documents/GitHub/40-days-devops-project/day4-dockercompose  # Path to the directory containing your Flask API Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    depends_on:
      - redis-cache
    environment:
      REDIS_HOST: redis-cache  # Use the service name as the hostname

  redis-cache:
    image: redis:latest  # Use an official Redis image
    environment:
      REDIS_PASSWORD: "access"  # Set an environment variable for Redis
